<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RunAnalyzersDuringBuild>False</RunAnalyzersDuringBuild>
    <RunAnalyzersDuringLiveAnalysis>False</RunAnalyzersDuringLiveAnalysis>
    <EnableNETAnalyzers>False</EnableNETAnalyzers>
    <ApplicationIcon>Icon.ico</ApplicationIcon>
    <AssemblyName>Programabara</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Document\**" />
    <EmbeddedResource Remove="Document\**" />
    <None Remove="Document\**" />
    <Page Remove="Document\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="_Source\Utils\UtilsTasks.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="BotonNew.png" />
    <None Remove="ButtonClose.png" />
    <None Remove="ButtonMoveDown.png" />
    <None Remove="ButtonMoveUp.png" />
    <None Remove="ButtonWarning.png" />
    <None Remove="Fonts\ComicRelief-Bold.ttf" />
    <None Remove="Fonts\ComicRelief.ttf" />
    <None Remove="Fonts\Germano-Bold.otf" />
    <None Remove="Fonts\Germano-BoldOblique.otf" />
    <None Remove="Fonts\Germano-Italic.otf" />
    <None Remove="Fonts\Germano-Regular.otf" />
    <None Remove="Fonts\Roboto-Bold.ttf" />
    <None Remove="Fonts\Roboto-BoldItalic.ttf" />
    <None Remove="Fonts\Roboto-Italic.ttf" />
    <None Remove="Fonts\Roboto-Regular.ttf" />
    <None Remove="Fonts\RobotoMono-Bold.ttf" />
    <None Remove="Fonts\RobotoMono-BoldItalic.ttf" />
    <None Remove="Fonts\RobotoMono-Italic.ttf" />
    <None Remove="Fonts\RobotoMono-Regular.ttf" />
    <None Remove="IconEdit.png" />
    <None Remove="Images\Background.jpg" />
    <None Remove="Images\Background04.jpg" />
    <None Remove="Images\BackgroundAbout.jpg" />
    <None Remove="Images\BackgroundClouds.jpg" />
    <None Remove="Images\BackgroundSteps.jpg" />
    <None Remove="Images\BackgroundTitle.png" />
    <None Remove="Images\ButonReferenceAdd.png" />
    <None Remove="Images\ButonReferenceRemove.png" />
    <None Remove="Images\ButonReferenceSetBig.png" />
    <None Remove="Images\ButtonAbout.png" />
    <None Remove="Images\ButtonAccept.png" />
    <None Remove="Images\ButtonBigGenerateDoc.png" />
    <None Remove="Images\ButtonCancel.png" />
    <None Remove="Images\ButtonDeleteMedium.png" />
    <None Remove="Images\ButtonEditMedium.png" />
    <None Remove="Images\ButtonFolder.png" />
    <None Remove="Images\ButtonHelp.png" />
    <None Remove="Images\ButtonNewMedium.png" />
    <None Remove="Images\ButtonNo.png" />
    <None Remove="Images\ButtonPick.png" />
    <None Remove="Images\ButtonReferenceAddBig.png" />
    <None Remove="Images\ButtonReset.png" />
    <None Remove="Images\ButtonStorageFolder.png" />
    <None Remove="Images\ButtonYes.png" />
    <None Remove="Images\ButtonZipExport.png" />
    <None Remove="Images\ButtonZipImport.png" />
    <None Remove="Images\CaptionColor.png" />
    <None Remove="Images\CaptionHeight.png" />
    <None Remove="Images\CaptionPaddingBottom.png" />
    <None Remove="Images\CaptionPaddingLeft.png" />
    <None Remove="Images\CaptionPaddingRight.png" />
    <None Remove="Images\CaptionPaddingTop.png" />
    <None Remove="Images\CaptionPositionX.png" />
    <None Remove="Images\CaptionPositionY.png" />
    <None Remove="Images\CaptionSeparationBottom.png" />
    <None Remove="Images\CaptionSeparationLeft.png" />
    <None Remove="Images\CaptionSeparationRight.png" />
    <None Remove="Images\CaptionSeparationTop.png" />
    <None Remove="Images\CaptionWidth.png" />
    <None Remove="Images\IconInfo.png" />
    <None Remove="Images\IconQuestion.png" />
    <None Remove="Images\IconWarning.png" />
    <None Remove="Images\ValidatorCapyBig.png" />
    <None Remove="Packages\Tutorial.zip" />
  </ItemGroup>

  <ItemGroup>
    <COMReference Include="Microsoft.Office.Interop.Word">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>7</VersionMinor>
      <VersionMajor>8</VersionMajor>
      <Guid>00020905-0000-0000-c000-000000000046</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>
    <COMReference Include="MSHTML">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>0</VersionMinor>
      <VersionMajor>4</VersionMajor>
      <Guid>3050f1c5-98b5-11cf-bb82-00aa00bdce0b</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>
    <COMReference Include="Microsoft.Office.Core">
      <WrapperTool>primary</WrapperTool>
      <VersionMinor>8</VersionMinor>
      <VersionMajor>2</VersionMajor>
      <Guid>2df8d04c-5bfa-101b-bde5-00aa0044de52</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>True</EmbedInteropTypes>
    </COMReference>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Icon.ico" />
    <Content Include="Packages\Tutorial.zip">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Fonts\ComicRelief-Bold.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\ComicRelief.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Germano-Bold.otf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Germano-BoldOblique.otf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Germano-Italic.otf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Germano-Regular.otf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Roboto-Bold.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Roboto-BoldItalic.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Roboto-Italic.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\Roboto-Regular.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\RobotoMono-Bold.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\RobotoMono-BoldItalic.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\RobotoMono-Italic.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Fonts\RobotoMono-Regular.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Background.jpg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\BackgroundAbout.jpg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\BackgroundClouds.jpg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\BackgroundSteps.jpg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\BackgroundTitle.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\ButonReferenceAdd.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\ButonReferenceRemove.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\ButonReferenceSetBig.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\ButtonAbout.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\ButtonBigGenerateDoc.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\ButtonDeleteMedium.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\ButtonEditMedium.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\ButtonFolder.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\ButtonHelp.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\ButtonMoveDown.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\ButtonMoveUp.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\ButtonAccept.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\ButtonCancel.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\ButtonClose.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\ButtonDelete.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\ButtonEdit.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\ButtonNew.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\ButtonNewMedium.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\ButtonNo.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\ButtonPick.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\ButtonReferenceAddBig.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\ButtonReset.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\ButtonStorageFolder.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\ButtonWarning.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\ButtonYes.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\ButtonZipExport.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\ButtonZipImport.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\CaptionColor.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\CaptionHeight.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\CaptionPaddingBottom.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\CaptionPaddingLeft.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\CaptionPaddingRight.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\CaptionPaddingTop.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\CaptionPositionX.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\CaptionPositionY.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\CaptionSeparationBottom.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\CaptionSeparationLeft.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\CaptionSeparationRight.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\CaptionSeparationTop.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\CaptionWidth.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\IconInfo.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\IconQuestion.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\IconWarning.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\ValidatorCapyBig.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
